<?xml version="1.0" ?>

<!--Generates a urdf from the macro in kr210_macro.xacro -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="rail_cross_section" value="0.1"/>
<xacro:property name="workcell_width" value="5.0"/>
<xacro:property name="workcell_length" value="8.0"/>
<xacro:property name="workcell_height" value="3.0"/>
<xacro:property name="workcell_thickness" value="0.01"/>
<xacro:property name="workcell_z" value="-0.1"/>

<xacro:macro name="ucla_linear_track_demo_cell" params="prefix">
  <link name="demo_cell_base_link"/>

  <material name="workcell_material">
   <color rgba="0.8 1.0 0.8 0.2"/>
  </material>

  <link name="workcell_bounds">
    <!-- visual geometries -->
    <!--<visual> --><!-- top -->
    <!-- <origin xyz="0 0 ${workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_width} ${workcell_thickness}"/>
      </geometry>
      <material name="workcell_material"/>
    </visual> -->
    <visual><!-- right ( +x ) -->
      <origin xyz="${0.5*workcell_length} 0 ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_thickness} ${workcell_width} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </visual>
    <visual><!-- bottom -->
      <material name="workcell_material"/>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${workcell_length} ${workcell_width} ${workcell_thickness}"/>
      </geometry>
    </visual>
    <visual><!-- left ( -x ) -->
      <origin xyz="${-0.5*workcell_length} 0 ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_thickness} ${workcell_width} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </visual>
    <!--<visual>--> <!-- front ( +y ) -->
      <!--<origin xyz="0 ${0.5*workcell_width} ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_thickness} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </visual>-->
    <visual><!-- rear ( -y ) -->
      <origin xyz="0 ${-0.5*workcell_width} ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_thickness} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </visual> 

    <!-- collision geometries -->
    <collision><!-- top -->
      <origin xyz="0 0 ${workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_width} ${workcell_thickness}"/>
      </geometry>
      <material name="workcell_material"/>
    </collision>
    <collision><!-- right ( +x ) -->
      <origin xyz="${0.5*workcell_length} 0 ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_thickness} ${workcell_width} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </collision>
    <collision><!-- bottom -->
      <material name="workcell_material"/>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${workcell_length} ${workcell_width} ${workcell_thickness}"/>
      </geometry>
    </collision>
    <collision><!-- left ( -x ) -->
      <origin xyz="${-0.5*workcell_length} 0 ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_thickness} ${workcell_width} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </collision>
    <collision><!-- front ( +y ) -->
      <origin xyz="0 ${0.5*workcell_width} ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_thickness} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </collision>
    <collision><!-- rear ( -y ) -->
      <origin xyz="0 ${-0.5*workcell_width} ${0.5*workcell_height}"/>
      <geometry>
        <box size="${workcell_length} ${workcell_thickness} ${workcell_height}"/>
      </geometry>
      <material name="workcell_material"/>
    </collision>  
  </link>

  <link name="rail">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="4 ${rail_cross_section} ${rail_cross_section}"/>
      </geometry>
      <material name="yellow">
       <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="4 0.1 0.1"/>
      </geometry>
      <material name="yellow">
       <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </collision>   
  </link>

  <joint name="cell_base_to_bounds" type="fixed">
    <parent link="demo_cell_base_link" />
    <child link="workcell_bounds" />
    <origin xyz="0 0 ${workcell_z}"/>
  </joint>

  <joint name="cell_base_to_rail" type="fixed">
    <parent link="demo_cell_base_link" />
    <child link="rail" />
    <origin xyz="0 0 0"/>
  </joint>

  <joint name="rail_to_robot_base_link" type="prismatic">
    <parent link="rail" />
    <child link="base_link" />
    <origin xyz="0 0 ${0.5*rail_cross_section}"/>
    <axis xyz="1 0 0"/>
    <limit lower="-2" upper="2" effort="1" velocity="1"/>
  </joint>

</xacro:macro>
</robot>
